"""Generate curl command examples from endpoints."""
from __future__ import annotations

import json
from pathlib import Path

from apkre.session import Session


class CurlBuilder:
    """Write a shell script of curl examples for all discovered endpoints."""

    def __init__(self, endpoints: list[dict], session: Session) -> None:
        self.endpoints = endpoints
        self.session = session

    def build(self) -> str:
        apk_name = Path(self.session.apk_path).stem
        lines = [
            "#!/usr/bin/env bash",
            f"# curl examples — {apk_name} API",
            "# Generated by apkre — APK Reverse Engineering Platform",
            "",
            "# Set your bearer token:",
            f'TOKEN="${{APKRE_TOKEN:-{self.session.tokens[0] if self.session.tokens else "<paste token here>"}}}"',
            "",
        ]

        for ep in sorted(self.endpoints, key=lambda e: e.get("path", "")):
            method = ep.get("method", "GET").upper()
            host = ep.get("host", "api.example.com")
            path = ep.get("path", "/")
            auth = ep.get("auth", False)

            url = f"https://{host}{path}"

            cmd_parts = ["curl", "-s", "-X", method]

            if auth:
                cmd_parts += ['-H', '"Authorization: Bearer $TOKEN"']

            cmd_parts += ['-H', '"Content-Type: application/json"']

            if ep.get("request_body") and method in ("POST", "PUT", "PATCH"):
                body_json = json.dumps(ep["request_body"], separators=(",", ":"))
                cmd_parts += ["--data", f"'{body_json}'"]

            cmd_parts.append(f'"{url}"')

            lines.append(f"# {method} {path}")
            if ep.get("response_schema"):
                lines.append(f"# Response schema inferred from live capture")
            lines.append(" \\\n  ".join(cmd_parts))
            lines.append("")

        return "\n".join(lines)

    def write(self, path: str) -> None:
        content = self.build()
        Path(path).write_text(content)
        Path(path).chmod(0o755)
