"""Build OpenAPI 3.0 spec from merged endpoints."""
from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

import yaml

from apkre.session import Session


class OpenApiBuilder:
    """Generate an OpenAPI 3.0 YAML spec from discovered endpoints."""

    def __init__(self, endpoints: list[dict], session: Session) -> None:
        self.endpoints = endpoints
        self.session = session

    def build(self) -> dict:
        # Detect base server from most common host
        host_counts: dict[str, int] = defaultdict(int)
        for ep in self.endpoints:
            if ep.get("host"):
                host_counts[ep["host"]] += 1

        if host_counts:
            primary_host = max(host_counts, key=host_counts.__getitem__)
        else:
            primary_host = "api.example.com"

        spec: dict = {
            "openapi": "3.0.0",
            "info": {
                "title": f"{Path(self.session.apk_path).stem} API",
                "version": "discovered",
                "description": (
                    "Auto-generated by apkre — APK Reverse Engineering Platform. "
                    "Schemas and endpoint list were discovered via static analysis "
                    "and dynamic SSL interception."
                ),
            },
            "servers": [{"url": f"https://{primary_host}"}],
            "security": [{"bearerAuth": []}],
            "components": {
                "securitySchemes": {
                    "bearerAuth": {
                        "type": "http",
                        "scheme": "bearer",
                        "bearerFormat": "JWT",
                        **({"x-sample-token": self.session.tokens[0]} if self.session.tokens else {}),
                    }
                }
            },
            "paths": {},
        }

        # Additional servers if multiple hosts
        extra_hosts = [h for h in host_counts if h != primary_host]
        for h in sorted(extra_hosts):
            spec["servers"].append({"url": f"https://{h}"})

        for ep in self.endpoints:
            path = ep.get("path", "/")
            method = ep.get("method", "GET").lower()
            if method == "?":
                method = "get"

            operation = self._build_operation(ep)

            if path not in spec["paths"]:
                spec["paths"][path] = {}
            spec["paths"][path][method] = operation

        return spec

    def _build_operation(self, ep: dict) -> dict:
        """Build a single path operation object."""
        # Path parameters
        param_names = re.findall(r'\{([^}]+)\}', ep.get("path", ""))
        params = [
            {
                "name": name,
                "in": "path",
                "required": True,
                "schema": {"type": "string"},
            }
            for name in param_names
        ]

        operation: dict = {
            "summary": _summary_from_path(ep.get("path", "/")),
            "operationId": _operation_id(ep),
            "tags": [_tag_from_path(ep.get("path", "/"))],
            "responses": {
                "200": {"description": "Success"},
                "401": {"description": "Unauthorized"},
            },
        }

        if params:
            operation["parameters"] = params

        if ep.get("auth"):
            operation["security"] = [{"bearerAuth": []}]
        else:
            operation["security"] = []

        # Request body
        if ep.get("request_schema") and ep.get("method", "GET") in ("POST", "PUT", "PATCH"):
            operation["requestBody"] = {
                "required": True,
                "content": {
                    "application/json": {"schema": ep["request_schema"]}
                },
            }

        # Response schema
        if ep.get("response_schema"):
            operation["responses"]["200"] = {
                "description": "Success",
                "content": {
                    "application/json": {"schema": ep["response_schema"]}
                },
            }

        # Source annotation
        operation["x-source"] = ep.get("source", "unknown")
        if ep.get("status"):
            operation["x-observed-status"] = ep["status"]

        return operation

    def write(self, path: str) -> None:
        spec = self.build()
        with open(path, "w") as f:
            yaml.dump(spec, f, default_flow_style=False, allow_unicode=True, sort_keys=False)


def _summary_from_path(path: str) -> str:
    parts = [p for p in path.strip("/").split("/") if p and not p.startswith("{")]
    if parts:
        return " ".join(p.replace("-", " ").replace("_", " ").title() for p in parts[-2:])
    return "API endpoint"


def _tag_from_path(path: str) -> str:
    parts = [p for p in path.strip("/").split("/") if p and not p.startswith("{")]
    return parts[0].title() if parts else "default"


def _operation_id(ep: dict) -> str:
    method = ep.get("method", "get").lower()
    parts = [p for p in ep.get("path", "/").strip("/").split("/") if p]
    clean = [re.sub(r'[^a-zA-Z0-9]', '_', p) for p in parts]
    return f"{method}_{'_'.join(clean)}" if clean else f"{method}_root"
