"""Build Postman Collection v2.1 from merged endpoints."""
from __future__ import annotations

import json
import re
import uuid
from collections import defaultdict
from pathlib import Path

from apkre.session import Session


class PostmanBuilder:
    """Generate a Postman Collection v2.1 JSON from discovered endpoints."""

    def __init__(self, endpoints: list[dict], session: Session) -> None:
        self.endpoints = endpoints
        self.session = session

    def build(self) -> dict:
        apk_name = Path(self.session.apk_path).stem
        collection: dict = {
            "info": {
                "_postman_id": str(uuid.uuid4()),
                "name": f"{apk_name} API",
                "description": "Auto-generated by apkre",
                "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
            },
            "auth": {
                "type": "bearer",
                "bearer": [{"key": "token", "value": "{{bearer_token}}", "type": "string"}],
            },
            "variable": [
                {"key": "bearer_token", "value": self.session.tokens[0] if self.session.tokens else "", "description": "Bearer token captured by apkre"},
            ],
            "item": [],
        }

        # Group by tag (first path segment)
        folders: dict[str, list[dict]] = defaultdict(list)
        for ep in self.endpoints:
            tag = _tag_from_path(ep.get("path", "/"))
            folders[tag].append(self._build_item(ep))

        for folder_name, items in sorted(folders.items()):
            collection["item"].append({
                "name": folder_name.title(),
                "item": items,
            })

        return collection

    def _build_item(self, ep: dict) -> dict:
        host = ep.get("host", "{{base_url}}")
        path = ep.get("path", "/")
        method = ep.get("method", "GET").upper()

        url_raw = f"https://{host}{path}"

        # Replace {id} placeholders with Postman variables
        url_raw = re.sub(r'\{([^}]+)\}', r':{{\1}}', url_raw)

        item: dict = {
            "name": f"{method} {path}",
            "request": {
                "method": method,
                "header": [],
                "url": {
                    "raw": url_raw,
                    "protocol": "https",
                    "host": host.split("."),
                    "path": [p for p in path.split("/") if p],
                },
            },
            "response": [],
        }

        if ep.get("auth"):
            item["request"]["auth"] = {
                "type": "bearer",
                "bearer": [{"key": "token", "value": "{{bearer_token}}", "type": "string"}],
            }

        if ep.get("request_body") and method in ("POST", "PUT", "PATCH"):
            item["request"]["body"] = {
                "mode": "raw",
                "raw": json.dumps(ep["request_body"], indent=2),
                "options": {"raw": {"language": "json"}},
            }
            item["request"]["header"].append({
                "key": "Content-Type", "value": "application/json",
            })

        return item

    def write(self, path: str) -> None:
        collection = self.build()
        with open(path, "w") as f:
            json.dump(collection, f, indent=2)


def _tag_from_path(path: str) -> str:
    parts = [p for p in path.strip("/").split("/") if p and not p.startswith("{")]
    return parts[0] if parts else "default"
