#!/usr/bin/env bash
# curl examples — bbl.intl.bambulab.com_base API
# Generated by apkre — APK Reverse Engineering Platform

# Set your bearer token:
TOKEN="${APKRE_TOKEN:-<REDACTED_TOKEN>}"

# GET /v1/analysis-st/tag/
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/analysis-st/tag/"

# GET /v1/comment-service/commentandrating
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/comment-service/commentandrating"

# GET /v1/design-recommend-service/my/for-you
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/design-recommend-service/my/for-you"

# GET /v1/design-service/contest/list
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/design-service/contest/list"

# GET /v1/design-service/design/{id}
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/design-service/design/{id}"

# GET /v1/design-service/design/{id}/remixed
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/design-service/design/{id}/remixed"

# GET /v1/design-service/my/design/favoriteslist
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/design-service/my/design/favoriteslist"

# GET /v1/design-user-service/my/preference
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/design-user-service/my/preference"

# GET /v1/design-user-service/my/profile
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/design-user-service/my/profile"

# GET /v1/iot-service/api/slicer/resource
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/iot-service/api/slicer/resource"

# GET /v1/iot-service/api/slicer/setting
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/iot-service/api/slicer/setting"

# GET /v1/iot-service/api/user/bind
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/iot-service/api/user/bind"

# GET /v1/operation-service/apphomepage
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/operation-service/apphomepage"

# GET /v1/operation-service/contest/133
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/operation-service/contest/133"

# GET /v1/operation-service/userContestDesign
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/operation-service/userContestDesign"

# GET /v1/point-service/boost/boostdesign
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/point-service/boost/boostdesign"

# GET /v1/search-service/cfg2
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/search-service/cfg2"

# GET /v1/search-service/design/{id}/relate
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/search-service/design/{id}/relate"

# GET /v1/search-service/homepage/nav
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/search-service/homepage/nav"

# GET /v1/search-service/recommand/youlike
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/search-service/recommand/youlike"

# GET /v1/search-service/select/design2
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/search-service/select/design2"

# GET /v1/user-service/latest/app
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/user-service/latest/app"

# GET /v1/user-service/my/message/count
curl \
  -s \
  -X \
  GET \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/user-service/my/message/count"

# POST /v1/user-service/my/message/device/taskstatus
curl \
  -s \
  -X \
  POST \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/user-service/my/message/device/taskstatus"

# POST /v1/user-service/user/devicetoken
curl \
  -s \
  -X \
  POST \
  -H \
  "Content-Type: application/json" \
  "https://api.bambulab.com/v1/user-service/user/devicetoken"
